/* soapAdvancedSecurityServiceBindingProxy.h
   Generated by gSOAP 2.8.82 for soap/onvif.h

gSOAP XML Web services tools
Copyright (C) 2000-2018, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#ifndef soapAdvancedSecurityServiceBindingProxy_H
#define soapAdvancedSecurityServiceBindingProxy_H
#include "soapH.h"

    class SOAP_CMAC AdvancedSecurityServiceBindingProxy {
      public:
        /// Context to manage proxy IO and data
        struct soap *soap;
        /// flag indicating that this context is owned by this proxy and should be deleted by the destructor
        bool soap_own;
        /// Endpoint URL of service 'AdvancedSecurityServiceBindingProxy' (change as needed)
        const char *soap_endpoint;
        /// Variables globally declared in soap/onvif.h, if any
        /// Construct a proxy with new managing context
        AdvancedSecurityServiceBindingProxy();
        /// Copy constructor
        AdvancedSecurityServiceBindingProxy(const AdvancedSecurityServiceBindingProxy& rhs);
        /// Construct proxy given a shared managing context
        AdvancedSecurityServiceBindingProxy(struct soap*);
        /// Construct proxy given a shared managing context and endpoint URL
        AdvancedSecurityServiceBindingProxy(struct soap*, const char *soap_endpoint_url);
        /// Constructor taking an endpoint URL
        AdvancedSecurityServiceBindingProxy(const char *soap_endpoint_url);
        /// Constructor taking input and output mode flags for the new managing context
        AdvancedSecurityServiceBindingProxy(soap_mode iomode);
        /// Constructor taking endpoint URL and input and output mode flags for the new managing context
        AdvancedSecurityServiceBindingProxy(const char *soap_endpoint_url, soap_mode iomode);
        /// Constructor taking input and output mode flags for the new managing context
        AdvancedSecurityServiceBindingProxy(soap_mode imode, soap_mode omode);
        /// Destructor deletes deserialized data and its managing context, when the context was allocated by the contructor
        virtual ~AdvancedSecurityServiceBindingProxy();
        /// Initializer used by constructors
        virtual void AdvancedSecurityServiceBindingProxy_init(soap_mode imode, soap_mode omode);
        /// Return a copy that has a new managing context with the same engine state
        virtual AdvancedSecurityServiceBindingProxy *copy();
        /// Copy assignment
        AdvancedSecurityServiceBindingProxy& operator=(const AdvancedSecurityServiceBindingProxy&);
        /// Delete all deserialized data (uses soap_destroy() and soap_end())
        virtual void destroy();
        /// Delete all deserialized data and reset to default
        virtual void reset();
        /// Disables and removes SOAP Header from message by setting soap->header = NULL
        virtual void soap_noheader();
        /// Add SOAP Header to message
        virtual void soap_header(struct _wsse__Security *wsse__Security, char *wsa5__MessageID, struct wsa5__RelatesToType *wsa5__RelatesTo, struct wsa5__EndpointReferenceType *wsa5__From, struct wsa5__EndpointReferenceType *wsa5__ReplyTo, struct wsa5__EndpointReferenceType *wsa5__FaultTo, char *wsa5__To, char *wsa5__Action, struct chan__ChannelInstanceType *chan__ChannelInstance, struct wsdd__AppSequenceType *wsdd__AppSequence);
        /// Get SOAP Header structure (i.e. soap->header, which is NULL when absent)
        virtual ::SOAP_ENV__Header *soap_header();
        /// Get SOAP Fault structure (i.e. soap->fault, which is NULL when absent)
        virtual ::SOAP_ENV__Fault *soap_fault();
        /// Get SOAP Fault subcode QName string (NULL when absent)
        virtual const char *soap_fault_subcode();
        /// Get SOAP Fault string/reason (NULL when absent)
        virtual const char *soap_fault_string();
        /// Get SOAP Fault detail XML string (NULL when absent)
        virtual const char *soap_fault_detail();
        /// Close connection (normally automatic, except for send_X ops)
        virtual int soap_close_socket();
        /// Force close connection (can kill a thread blocked on IO)
        virtual int soap_force_close_socket();
        /// Print fault
        virtual void soap_print_fault(FILE*);
    #ifndef WITH_LEAN
    #ifndef WITH_COMPAT
        /// Print fault to stream
        virtual void soap_stream_fault(std::ostream&);
    #endif
        /// Write fault to buffer
        virtual char *soap_sprint_fault(char *buf, size_t len);
    #endif
        //
        /// Web service synchronous operation 'GetServiceCapabilities' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetServiceCapabilities(_ns1__GetServiceCapabilities *ns1__GetServiceCapabilities, _ns1__GetServiceCapabilitiesResponse &ns1__GetServiceCapabilitiesResponse) { return this->GetServiceCapabilities(NULL, NULL, ns1__GetServiceCapabilities, ns1__GetServiceCapabilitiesResponse); }
        /// Web service synchronous operation 'GetServiceCapabilities' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetServiceCapabilities(const char *soap_endpoint_url, const char *soap_action, _ns1__GetServiceCapabilities *ns1__GetServiceCapabilities, _ns1__GetServiceCapabilitiesResponse &ns1__GetServiceCapabilitiesResponse) { return this->send_GetServiceCapabilities(soap_endpoint_url, soap_action, ns1__GetServiceCapabilities) || this->recv_GetServiceCapabilities(ns1__GetServiceCapabilitiesResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetServiceCapabilities' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetServiceCapabilities(const char *soap_endpoint_url, const char *soap_action, _ns1__GetServiceCapabilities *ns1__GetServiceCapabilities);
        /// Web service asynchronous operation 'recv_GetServiceCapabilities' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetServiceCapabilities(_ns1__GetServiceCapabilitiesResponse &ns1__GetServiceCapabilitiesResponse);
        //
        /// Web service synchronous operation 'CreateRSAKeyPair' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int CreateRSAKeyPair(_ns1__CreateRSAKeyPair *ns1__CreateRSAKeyPair, _ns1__CreateRSAKeyPairResponse &ns1__CreateRSAKeyPairResponse) { return this->CreateRSAKeyPair(NULL, NULL, ns1__CreateRSAKeyPair, ns1__CreateRSAKeyPairResponse); }
        /// Web service synchronous operation 'CreateRSAKeyPair' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int CreateRSAKeyPair(const char *soap_endpoint_url, const char *soap_action, _ns1__CreateRSAKeyPair *ns1__CreateRSAKeyPair, _ns1__CreateRSAKeyPairResponse &ns1__CreateRSAKeyPairResponse) { return this->send_CreateRSAKeyPair(soap_endpoint_url, soap_action, ns1__CreateRSAKeyPair) || this->recv_CreateRSAKeyPair(ns1__CreateRSAKeyPairResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_CreateRSAKeyPair' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_CreateRSAKeyPair(const char *soap_endpoint_url, const char *soap_action, _ns1__CreateRSAKeyPair *ns1__CreateRSAKeyPair);
        /// Web service asynchronous operation 'recv_CreateRSAKeyPair' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_CreateRSAKeyPair(_ns1__CreateRSAKeyPairResponse &ns1__CreateRSAKeyPairResponse);
        //
        /// Web service synchronous operation 'UploadKeyPairInPKCS8' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int UploadKeyPairInPKCS8(_ns1__UploadKeyPairInPKCS8 *ns1__UploadKeyPairInPKCS8, _ns1__UploadKeyPairInPKCS8Response &ns1__UploadKeyPairInPKCS8Response) { return this->UploadKeyPairInPKCS8(NULL, NULL, ns1__UploadKeyPairInPKCS8, ns1__UploadKeyPairInPKCS8Response); }
        /// Web service synchronous operation 'UploadKeyPairInPKCS8' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int UploadKeyPairInPKCS8(const char *soap_endpoint_url, const char *soap_action, _ns1__UploadKeyPairInPKCS8 *ns1__UploadKeyPairInPKCS8, _ns1__UploadKeyPairInPKCS8Response &ns1__UploadKeyPairInPKCS8Response) { return this->send_UploadKeyPairInPKCS8(soap_endpoint_url, soap_action, ns1__UploadKeyPairInPKCS8) || this->recv_UploadKeyPairInPKCS8(ns1__UploadKeyPairInPKCS8Response) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_UploadKeyPairInPKCS8' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_UploadKeyPairInPKCS8(const char *soap_endpoint_url, const char *soap_action, _ns1__UploadKeyPairInPKCS8 *ns1__UploadKeyPairInPKCS8);
        /// Web service asynchronous operation 'recv_UploadKeyPairInPKCS8' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_UploadKeyPairInPKCS8(_ns1__UploadKeyPairInPKCS8Response &ns1__UploadKeyPairInPKCS8Response);
        //
        /// Web service synchronous operation 'UploadCertificateWithPrivateKeyInPKCS12' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int UploadCertificateWithPrivateKeyInPKCS12(_ns1__UploadCertificateWithPrivateKeyInPKCS12 *ns1__UploadCertificateWithPrivateKeyInPKCS12, _ns1__UploadCertificateWithPrivateKeyInPKCS12Response &ns1__UploadCertificateWithPrivateKeyInPKCS12Response) { return this->UploadCertificateWithPrivateKeyInPKCS12(NULL, NULL, ns1__UploadCertificateWithPrivateKeyInPKCS12, ns1__UploadCertificateWithPrivateKeyInPKCS12Response); }
        /// Web service synchronous operation 'UploadCertificateWithPrivateKeyInPKCS12' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int UploadCertificateWithPrivateKeyInPKCS12(const char *soap_endpoint_url, const char *soap_action, _ns1__UploadCertificateWithPrivateKeyInPKCS12 *ns1__UploadCertificateWithPrivateKeyInPKCS12, _ns1__UploadCertificateWithPrivateKeyInPKCS12Response &ns1__UploadCertificateWithPrivateKeyInPKCS12Response) { return this->send_UploadCertificateWithPrivateKeyInPKCS12(soap_endpoint_url, soap_action, ns1__UploadCertificateWithPrivateKeyInPKCS12) || this->recv_UploadCertificateWithPrivateKeyInPKCS12(ns1__UploadCertificateWithPrivateKeyInPKCS12Response) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_UploadCertificateWithPrivateKeyInPKCS12' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_UploadCertificateWithPrivateKeyInPKCS12(const char *soap_endpoint_url, const char *soap_action, _ns1__UploadCertificateWithPrivateKeyInPKCS12 *ns1__UploadCertificateWithPrivateKeyInPKCS12);
        /// Web service asynchronous operation 'recv_UploadCertificateWithPrivateKeyInPKCS12' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_UploadCertificateWithPrivateKeyInPKCS12(_ns1__UploadCertificateWithPrivateKeyInPKCS12Response &ns1__UploadCertificateWithPrivateKeyInPKCS12Response);
        //
        /// Web service synchronous operation 'GetKeyStatus' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetKeyStatus(_ns1__GetKeyStatus *ns1__GetKeyStatus, _ns1__GetKeyStatusResponse &ns1__GetKeyStatusResponse) { return this->GetKeyStatus(NULL, NULL, ns1__GetKeyStatus, ns1__GetKeyStatusResponse); }
        /// Web service synchronous operation 'GetKeyStatus' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetKeyStatus(const char *soap_endpoint_url, const char *soap_action, _ns1__GetKeyStatus *ns1__GetKeyStatus, _ns1__GetKeyStatusResponse &ns1__GetKeyStatusResponse) { return this->send_GetKeyStatus(soap_endpoint_url, soap_action, ns1__GetKeyStatus) || this->recv_GetKeyStatus(ns1__GetKeyStatusResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetKeyStatus' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetKeyStatus(const char *soap_endpoint_url, const char *soap_action, _ns1__GetKeyStatus *ns1__GetKeyStatus);
        /// Web service asynchronous operation 'recv_GetKeyStatus' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetKeyStatus(_ns1__GetKeyStatusResponse &ns1__GetKeyStatusResponse);
        //
        /// Web service synchronous operation 'GetPrivateKeyStatus' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetPrivateKeyStatus(_ns1__GetPrivateKeyStatus *ns1__GetPrivateKeyStatus, _ns1__GetPrivateKeyStatusResponse &ns1__GetPrivateKeyStatusResponse) { return this->GetPrivateKeyStatus(NULL, NULL, ns1__GetPrivateKeyStatus, ns1__GetPrivateKeyStatusResponse); }
        /// Web service synchronous operation 'GetPrivateKeyStatus' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetPrivateKeyStatus(const char *soap_endpoint_url, const char *soap_action, _ns1__GetPrivateKeyStatus *ns1__GetPrivateKeyStatus, _ns1__GetPrivateKeyStatusResponse &ns1__GetPrivateKeyStatusResponse) { return this->send_GetPrivateKeyStatus(soap_endpoint_url, soap_action, ns1__GetPrivateKeyStatus) || this->recv_GetPrivateKeyStatus(ns1__GetPrivateKeyStatusResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetPrivateKeyStatus' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetPrivateKeyStatus(const char *soap_endpoint_url, const char *soap_action, _ns1__GetPrivateKeyStatus *ns1__GetPrivateKeyStatus);
        /// Web service asynchronous operation 'recv_GetPrivateKeyStatus' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetPrivateKeyStatus(_ns1__GetPrivateKeyStatusResponse &ns1__GetPrivateKeyStatusResponse);
        //
        /// Web service synchronous operation 'GetAllKeys' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetAllKeys(_ns1__GetAllKeys *ns1__GetAllKeys, _ns1__GetAllKeysResponse &ns1__GetAllKeysResponse) { return this->GetAllKeys(NULL, NULL, ns1__GetAllKeys, ns1__GetAllKeysResponse); }
        /// Web service synchronous operation 'GetAllKeys' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetAllKeys(const char *soap_endpoint_url, const char *soap_action, _ns1__GetAllKeys *ns1__GetAllKeys, _ns1__GetAllKeysResponse &ns1__GetAllKeysResponse) { return this->send_GetAllKeys(soap_endpoint_url, soap_action, ns1__GetAllKeys) || this->recv_GetAllKeys(ns1__GetAllKeysResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetAllKeys' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetAllKeys(const char *soap_endpoint_url, const char *soap_action, _ns1__GetAllKeys *ns1__GetAllKeys);
        /// Web service asynchronous operation 'recv_GetAllKeys' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetAllKeys(_ns1__GetAllKeysResponse &ns1__GetAllKeysResponse);
        //
        /// Web service synchronous operation 'DeleteKey' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int DeleteKey(_ns1__DeleteKey *ns1__DeleteKey, _ns1__DeleteKeyResponse &ns1__DeleteKeyResponse) { return this->DeleteKey(NULL, NULL, ns1__DeleteKey, ns1__DeleteKeyResponse); }
        /// Web service synchronous operation 'DeleteKey' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int DeleteKey(const char *soap_endpoint_url, const char *soap_action, _ns1__DeleteKey *ns1__DeleteKey, _ns1__DeleteKeyResponse &ns1__DeleteKeyResponse) { return this->send_DeleteKey(soap_endpoint_url, soap_action, ns1__DeleteKey) || this->recv_DeleteKey(ns1__DeleteKeyResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_DeleteKey' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_DeleteKey(const char *soap_endpoint_url, const char *soap_action, _ns1__DeleteKey *ns1__DeleteKey);
        /// Web service asynchronous operation 'recv_DeleteKey' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_DeleteKey(_ns1__DeleteKeyResponse &ns1__DeleteKeyResponse);
        //
        /// Web service synchronous operation 'CreatePKCS10CSR' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int CreatePKCS10CSR(_ns1__CreatePKCS10CSR *ns1__CreatePKCS10CSR, _ns1__CreatePKCS10CSRResponse &ns1__CreatePKCS10CSRResponse) { return this->CreatePKCS10CSR(NULL, NULL, ns1__CreatePKCS10CSR, ns1__CreatePKCS10CSRResponse); }
        /// Web service synchronous operation 'CreatePKCS10CSR' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int CreatePKCS10CSR(const char *soap_endpoint_url, const char *soap_action, _ns1__CreatePKCS10CSR *ns1__CreatePKCS10CSR, _ns1__CreatePKCS10CSRResponse &ns1__CreatePKCS10CSRResponse) { return this->send_CreatePKCS10CSR(soap_endpoint_url, soap_action, ns1__CreatePKCS10CSR) || this->recv_CreatePKCS10CSR(ns1__CreatePKCS10CSRResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_CreatePKCS10CSR' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_CreatePKCS10CSR(const char *soap_endpoint_url, const char *soap_action, _ns1__CreatePKCS10CSR *ns1__CreatePKCS10CSR);
        /// Web service asynchronous operation 'recv_CreatePKCS10CSR' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_CreatePKCS10CSR(_ns1__CreatePKCS10CSRResponse &ns1__CreatePKCS10CSRResponse);
        //
        /// Web service synchronous operation 'CreateSelfSignedCertificate' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int CreateSelfSignedCertificate(_ns1__CreateSelfSignedCertificate *ns1__CreateSelfSignedCertificate, _ns1__CreateSelfSignedCertificateResponse &ns1__CreateSelfSignedCertificateResponse) { return this->CreateSelfSignedCertificate(NULL, NULL, ns1__CreateSelfSignedCertificate, ns1__CreateSelfSignedCertificateResponse); }
        /// Web service synchronous operation 'CreateSelfSignedCertificate' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int CreateSelfSignedCertificate(const char *soap_endpoint_url, const char *soap_action, _ns1__CreateSelfSignedCertificate *ns1__CreateSelfSignedCertificate, _ns1__CreateSelfSignedCertificateResponse &ns1__CreateSelfSignedCertificateResponse) { return this->send_CreateSelfSignedCertificate(soap_endpoint_url, soap_action, ns1__CreateSelfSignedCertificate) || this->recv_CreateSelfSignedCertificate(ns1__CreateSelfSignedCertificateResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_CreateSelfSignedCertificate' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_CreateSelfSignedCertificate(const char *soap_endpoint_url, const char *soap_action, _ns1__CreateSelfSignedCertificate *ns1__CreateSelfSignedCertificate);
        /// Web service asynchronous operation 'recv_CreateSelfSignedCertificate' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_CreateSelfSignedCertificate(_ns1__CreateSelfSignedCertificateResponse &ns1__CreateSelfSignedCertificateResponse);
        //
        /// Web service synchronous operation 'UploadCertificate' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int UploadCertificate(_ns1__UploadCertificate *ns1__UploadCertificate, _ns1__UploadCertificateResponse &ns1__UploadCertificateResponse) { return this->UploadCertificate(NULL, NULL, ns1__UploadCertificate, ns1__UploadCertificateResponse); }
        /// Web service synchronous operation 'UploadCertificate' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int UploadCertificate(const char *soap_endpoint_url, const char *soap_action, _ns1__UploadCertificate *ns1__UploadCertificate, _ns1__UploadCertificateResponse &ns1__UploadCertificateResponse) { return this->send_UploadCertificate(soap_endpoint_url, soap_action, ns1__UploadCertificate) || this->recv_UploadCertificate(ns1__UploadCertificateResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_UploadCertificate' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_UploadCertificate(const char *soap_endpoint_url, const char *soap_action, _ns1__UploadCertificate *ns1__UploadCertificate);
        /// Web service asynchronous operation 'recv_UploadCertificate' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_UploadCertificate(_ns1__UploadCertificateResponse &ns1__UploadCertificateResponse);
        //
        /// Web service synchronous operation 'GetCertificate' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetCertificate(_ns1__GetCertificate *ns1__GetCertificate, _ns1__GetCertificateResponse &ns1__GetCertificateResponse) { return this->GetCertificate(NULL, NULL, ns1__GetCertificate, ns1__GetCertificateResponse); }
        /// Web service synchronous operation 'GetCertificate' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetCertificate(const char *soap_endpoint_url, const char *soap_action, _ns1__GetCertificate *ns1__GetCertificate, _ns1__GetCertificateResponse &ns1__GetCertificateResponse) { return this->send_GetCertificate(soap_endpoint_url, soap_action, ns1__GetCertificate) || this->recv_GetCertificate(ns1__GetCertificateResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetCertificate' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetCertificate(const char *soap_endpoint_url, const char *soap_action, _ns1__GetCertificate *ns1__GetCertificate);
        /// Web service asynchronous operation 'recv_GetCertificate' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetCertificate(_ns1__GetCertificateResponse &ns1__GetCertificateResponse);
        //
        /// Web service synchronous operation 'GetAllCertificates' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetAllCertificates(_ns1__GetAllCertificates *ns1__GetAllCertificates, _ns1__GetAllCertificatesResponse &ns1__GetAllCertificatesResponse) { return this->GetAllCertificates(NULL, NULL, ns1__GetAllCertificates, ns1__GetAllCertificatesResponse); }
        /// Web service synchronous operation 'GetAllCertificates' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetAllCertificates(const char *soap_endpoint_url, const char *soap_action, _ns1__GetAllCertificates *ns1__GetAllCertificates, _ns1__GetAllCertificatesResponse &ns1__GetAllCertificatesResponse) { return this->send_GetAllCertificates(soap_endpoint_url, soap_action, ns1__GetAllCertificates) || this->recv_GetAllCertificates(ns1__GetAllCertificatesResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetAllCertificates' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetAllCertificates(const char *soap_endpoint_url, const char *soap_action, _ns1__GetAllCertificates *ns1__GetAllCertificates);
        /// Web service asynchronous operation 'recv_GetAllCertificates' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetAllCertificates(_ns1__GetAllCertificatesResponse &ns1__GetAllCertificatesResponse);
        //
        /// Web service synchronous operation 'DeleteCertificate' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int DeleteCertificate(_ns1__DeleteCertificate *ns1__DeleteCertificate, _ns1__DeleteCertificateResponse &ns1__DeleteCertificateResponse) { return this->DeleteCertificate(NULL, NULL, ns1__DeleteCertificate, ns1__DeleteCertificateResponse); }
        /// Web service synchronous operation 'DeleteCertificate' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int DeleteCertificate(const char *soap_endpoint_url, const char *soap_action, _ns1__DeleteCertificate *ns1__DeleteCertificate, _ns1__DeleteCertificateResponse &ns1__DeleteCertificateResponse) { return this->send_DeleteCertificate(soap_endpoint_url, soap_action, ns1__DeleteCertificate) || this->recv_DeleteCertificate(ns1__DeleteCertificateResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_DeleteCertificate' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_DeleteCertificate(const char *soap_endpoint_url, const char *soap_action, _ns1__DeleteCertificate *ns1__DeleteCertificate);
        /// Web service asynchronous operation 'recv_DeleteCertificate' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_DeleteCertificate(_ns1__DeleteCertificateResponse &ns1__DeleteCertificateResponse);
        //
        /// Web service synchronous operation 'CreateCertificationPath' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int CreateCertificationPath(_ns1__CreateCertificationPath *ns1__CreateCertificationPath, _ns1__CreateCertificationPathResponse &ns1__CreateCertificationPathResponse) { return this->CreateCertificationPath(NULL, NULL, ns1__CreateCertificationPath, ns1__CreateCertificationPathResponse); }
        /// Web service synchronous operation 'CreateCertificationPath' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int CreateCertificationPath(const char *soap_endpoint_url, const char *soap_action, _ns1__CreateCertificationPath *ns1__CreateCertificationPath, _ns1__CreateCertificationPathResponse &ns1__CreateCertificationPathResponse) { return this->send_CreateCertificationPath(soap_endpoint_url, soap_action, ns1__CreateCertificationPath) || this->recv_CreateCertificationPath(ns1__CreateCertificationPathResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_CreateCertificationPath' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_CreateCertificationPath(const char *soap_endpoint_url, const char *soap_action, _ns1__CreateCertificationPath *ns1__CreateCertificationPath);
        /// Web service asynchronous operation 'recv_CreateCertificationPath' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_CreateCertificationPath(_ns1__CreateCertificationPathResponse &ns1__CreateCertificationPathResponse);
        //
        /// Web service synchronous operation 'GetCertificationPath' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetCertificationPath(_ns1__GetCertificationPath *ns1__GetCertificationPath, _ns1__GetCertificationPathResponse &ns1__GetCertificationPathResponse) { return this->GetCertificationPath(NULL, NULL, ns1__GetCertificationPath, ns1__GetCertificationPathResponse); }
        /// Web service synchronous operation 'GetCertificationPath' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetCertificationPath(const char *soap_endpoint_url, const char *soap_action, _ns1__GetCertificationPath *ns1__GetCertificationPath, _ns1__GetCertificationPathResponse &ns1__GetCertificationPathResponse) { return this->send_GetCertificationPath(soap_endpoint_url, soap_action, ns1__GetCertificationPath) || this->recv_GetCertificationPath(ns1__GetCertificationPathResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetCertificationPath' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetCertificationPath(const char *soap_endpoint_url, const char *soap_action, _ns1__GetCertificationPath *ns1__GetCertificationPath);
        /// Web service asynchronous operation 'recv_GetCertificationPath' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetCertificationPath(_ns1__GetCertificationPathResponse &ns1__GetCertificationPathResponse);
        //
        /// Web service synchronous operation 'GetAllCertificationPaths' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetAllCertificationPaths(_ns1__GetAllCertificationPaths *ns1__GetAllCertificationPaths, _ns1__GetAllCertificationPathsResponse &ns1__GetAllCertificationPathsResponse) { return this->GetAllCertificationPaths(NULL, NULL, ns1__GetAllCertificationPaths, ns1__GetAllCertificationPathsResponse); }
        /// Web service synchronous operation 'GetAllCertificationPaths' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetAllCertificationPaths(const char *soap_endpoint_url, const char *soap_action, _ns1__GetAllCertificationPaths *ns1__GetAllCertificationPaths, _ns1__GetAllCertificationPathsResponse &ns1__GetAllCertificationPathsResponse) { return this->send_GetAllCertificationPaths(soap_endpoint_url, soap_action, ns1__GetAllCertificationPaths) || this->recv_GetAllCertificationPaths(ns1__GetAllCertificationPathsResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetAllCertificationPaths' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetAllCertificationPaths(const char *soap_endpoint_url, const char *soap_action, _ns1__GetAllCertificationPaths *ns1__GetAllCertificationPaths);
        /// Web service asynchronous operation 'recv_GetAllCertificationPaths' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetAllCertificationPaths(_ns1__GetAllCertificationPathsResponse &ns1__GetAllCertificationPathsResponse);
        //
        /// Web service synchronous operation 'DeleteCertificationPath' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int DeleteCertificationPath(_ns1__DeleteCertificationPath *ns1__DeleteCertificationPath, _ns1__DeleteCertificationPathResponse &ns1__DeleteCertificationPathResponse) { return this->DeleteCertificationPath(NULL, NULL, ns1__DeleteCertificationPath, ns1__DeleteCertificationPathResponse); }
        /// Web service synchronous operation 'DeleteCertificationPath' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int DeleteCertificationPath(const char *soap_endpoint_url, const char *soap_action, _ns1__DeleteCertificationPath *ns1__DeleteCertificationPath, _ns1__DeleteCertificationPathResponse &ns1__DeleteCertificationPathResponse) { return this->send_DeleteCertificationPath(soap_endpoint_url, soap_action, ns1__DeleteCertificationPath) || this->recv_DeleteCertificationPath(ns1__DeleteCertificationPathResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_DeleteCertificationPath' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_DeleteCertificationPath(const char *soap_endpoint_url, const char *soap_action, _ns1__DeleteCertificationPath *ns1__DeleteCertificationPath);
        /// Web service asynchronous operation 'recv_DeleteCertificationPath' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_DeleteCertificationPath(_ns1__DeleteCertificationPathResponse &ns1__DeleteCertificationPathResponse);
        //
        /// Web service synchronous operation 'UploadPassphrase' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int UploadPassphrase(_ns1__UploadPassphrase *ns1__UploadPassphrase, _ns1__UploadPassphraseResponse &ns1__UploadPassphraseResponse) { return this->UploadPassphrase(NULL, NULL, ns1__UploadPassphrase, ns1__UploadPassphraseResponse); }
        /// Web service synchronous operation 'UploadPassphrase' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int UploadPassphrase(const char *soap_endpoint_url, const char *soap_action, _ns1__UploadPassphrase *ns1__UploadPassphrase, _ns1__UploadPassphraseResponse &ns1__UploadPassphraseResponse) { return this->send_UploadPassphrase(soap_endpoint_url, soap_action, ns1__UploadPassphrase) || this->recv_UploadPassphrase(ns1__UploadPassphraseResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_UploadPassphrase' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_UploadPassphrase(const char *soap_endpoint_url, const char *soap_action, _ns1__UploadPassphrase *ns1__UploadPassphrase);
        /// Web service asynchronous operation 'recv_UploadPassphrase' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_UploadPassphrase(_ns1__UploadPassphraseResponse &ns1__UploadPassphraseResponse);
        //
        /// Web service synchronous operation 'GetAllPassphrases' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetAllPassphrases(_ns1__GetAllPassphrases *ns1__GetAllPassphrases, _ns1__GetAllPassphrasesResponse &ns1__GetAllPassphrasesResponse) { return this->GetAllPassphrases(NULL, NULL, ns1__GetAllPassphrases, ns1__GetAllPassphrasesResponse); }
        /// Web service synchronous operation 'GetAllPassphrases' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetAllPassphrases(const char *soap_endpoint_url, const char *soap_action, _ns1__GetAllPassphrases *ns1__GetAllPassphrases, _ns1__GetAllPassphrasesResponse &ns1__GetAllPassphrasesResponse) { return this->send_GetAllPassphrases(soap_endpoint_url, soap_action, ns1__GetAllPassphrases) || this->recv_GetAllPassphrases(ns1__GetAllPassphrasesResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetAllPassphrases' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetAllPassphrases(const char *soap_endpoint_url, const char *soap_action, _ns1__GetAllPassphrases *ns1__GetAllPassphrases);
        /// Web service asynchronous operation 'recv_GetAllPassphrases' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetAllPassphrases(_ns1__GetAllPassphrasesResponse &ns1__GetAllPassphrasesResponse);
        //
        /// Web service synchronous operation 'DeletePassphrase' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int DeletePassphrase(_ns1__DeletePassphrase *ns1__DeletePassphrase, _ns1__DeletePassphraseResponse &ns1__DeletePassphraseResponse) { return this->DeletePassphrase(NULL, NULL, ns1__DeletePassphrase, ns1__DeletePassphraseResponse); }
        /// Web service synchronous operation 'DeletePassphrase' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int DeletePassphrase(const char *soap_endpoint_url, const char *soap_action, _ns1__DeletePassphrase *ns1__DeletePassphrase, _ns1__DeletePassphraseResponse &ns1__DeletePassphraseResponse) { return this->send_DeletePassphrase(soap_endpoint_url, soap_action, ns1__DeletePassphrase) || this->recv_DeletePassphrase(ns1__DeletePassphraseResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_DeletePassphrase' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_DeletePassphrase(const char *soap_endpoint_url, const char *soap_action, _ns1__DeletePassphrase *ns1__DeletePassphrase);
        /// Web service asynchronous operation 'recv_DeletePassphrase' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_DeletePassphrase(_ns1__DeletePassphraseResponse &ns1__DeletePassphraseResponse);
        //
        /// Web service synchronous operation 'UploadCRL' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int UploadCRL(_ns1__UploadCRL *ns1__UploadCRL, _ns1__UploadCRLResponse &ns1__UploadCRLResponse) { return this->UploadCRL(NULL, NULL, ns1__UploadCRL, ns1__UploadCRLResponse); }
        /// Web service synchronous operation 'UploadCRL' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int UploadCRL(const char *soap_endpoint_url, const char *soap_action, _ns1__UploadCRL *ns1__UploadCRL, _ns1__UploadCRLResponse &ns1__UploadCRLResponse) { return this->send_UploadCRL(soap_endpoint_url, soap_action, ns1__UploadCRL) || this->recv_UploadCRL(ns1__UploadCRLResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_UploadCRL' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_UploadCRL(const char *soap_endpoint_url, const char *soap_action, _ns1__UploadCRL *ns1__UploadCRL);
        /// Web service asynchronous operation 'recv_UploadCRL' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_UploadCRL(_ns1__UploadCRLResponse &ns1__UploadCRLResponse);
        //
        /// Web service synchronous operation 'GetCRL' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetCRL(_ns1__GetCRL *ns1__GetCRL, _ns1__GetCRLResponse &ns1__GetCRLResponse) { return this->GetCRL(NULL, NULL, ns1__GetCRL, ns1__GetCRLResponse); }
        /// Web service synchronous operation 'GetCRL' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetCRL(const char *soap_endpoint_url, const char *soap_action, _ns1__GetCRL *ns1__GetCRL, _ns1__GetCRLResponse &ns1__GetCRLResponse) { return this->send_GetCRL(soap_endpoint_url, soap_action, ns1__GetCRL) || this->recv_GetCRL(ns1__GetCRLResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetCRL' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetCRL(const char *soap_endpoint_url, const char *soap_action, _ns1__GetCRL *ns1__GetCRL);
        /// Web service asynchronous operation 'recv_GetCRL' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetCRL(_ns1__GetCRLResponse &ns1__GetCRLResponse);
        //
        /// Web service synchronous operation 'GetAllCRLs' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetAllCRLs(_ns1__GetAllCRLs *ns1__GetAllCRLs, _ns1__GetAllCRLsResponse &ns1__GetAllCRLsResponse) { return this->GetAllCRLs(NULL, NULL, ns1__GetAllCRLs, ns1__GetAllCRLsResponse); }
        /// Web service synchronous operation 'GetAllCRLs' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetAllCRLs(const char *soap_endpoint_url, const char *soap_action, _ns1__GetAllCRLs *ns1__GetAllCRLs, _ns1__GetAllCRLsResponse &ns1__GetAllCRLsResponse) { return this->send_GetAllCRLs(soap_endpoint_url, soap_action, ns1__GetAllCRLs) || this->recv_GetAllCRLs(ns1__GetAllCRLsResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetAllCRLs' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetAllCRLs(const char *soap_endpoint_url, const char *soap_action, _ns1__GetAllCRLs *ns1__GetAllCRLs);
        /// Web service asynchronous operation 'recv_GetAllCRLs' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetAllCRLs(_ns1__GetAllCRLsResponse &ns1__GetAllCRLsResponse);
        //
        /// Web service synchronous operation 'DeleteCRL' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int DeleteCRL(_ns1__DeleteCRL *ns1__DeleteCRL, _ns1__DeleteCRLResponse &ns1__DeleteCRLResponse) { return this->DeleteCRL(NULL, NULL, ns1__DeleteCRL, ns1__DeleteCRLResponse); }
        /// Web service synchronous operation 'DeleteCRL' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int DeleteCRL(const char *soap_endpoint_url, const char *soap_action, _ns1__DeleteCRL *ns1__DeleteCRL, _ns1__DeleteCRLResponse &ns1__DeleteCRLResponse) { return this->send_DeleteCRL(soap_endpoint_url, soap_action, ns1__DeleteCRL) || this->recv_DeleteCRL(ns1__DeleteCRLResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_DeleteCRL' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_DeleteCRL(const char *soap_endpoint_url, const char *soap_action, _ns1__DeleteCRL *ns1__DeleteCRL);
        /// Web service asynchronous operation 'recv_DeleteCRL' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_DeleteCRL(_ns1__DeleteCRLResponse &ns1__DeleteCRLResponse);
        //
        /// Web service synchronous operation 'CreateCertPathValidationPolicy' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int CreateCertPathValidationPolicy(_ns1__CreateCertPathValidationPolicy *ns1__CreateCertPathValidationPolicy, _ns1__CreateCertPathValidationPolicyResponse &ns1__CreateCertPathValidationPolicyResponse) { return this->CreateCertPathValidationPolicy(NULL, NULL, ns1__CreateCertPathValidationPolicy, ns1__CreateCertPathValidationPolicyResponse); }
        /// Web service synchronous operation 'CreateCertPathValidationPolicy' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int CreateCertPathValidationPolicy(const char *soap_endpoint_url, const char *soap_action, _ns1__CreateCertPathValidationPolicy *ns1__CreateCertPathValidationPolicy, _ns1__CreateCertPathValidationPolicyResponse &ns1__CreateCertPathValidationPolicyResponse) { return this->send_CreateCertPathValidationPolicy(soap_endpoint_url, soap_action, ns1__CreateCertPathValidationPolicy) || this->recv_CreateCertPathValidationPolicy(ns1__CreateCertPathValidationPolicyResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_CreateCertPathValidationPolicy' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_CreateCertPathValidationPolicy(const char *soap_endpoint_url, const char *soap_action, _ns1__CreateCertPathValidationPolicy *ns1__CreateCertPathValidationPolicy);
        /// Web service asynchronous operation 'recv_CreateCertPathValidationPolicy' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_CreateCertPathValidationPolicy(_ns1__CreateCertPathValidationPolicyResponse &ns1__CreateCertPathValidationPolicyResponse);
        //
        /// Web service synchronous operation 'GetCertPathValidationPolicy' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetCertPathValidationPolicy(_ns1__GetCertPathValidationPolicy *ns1__GetCertPathValidationPolicy, _ns1__GetCertPathValidationPolicyResponse &ns1__GetCertPathValidationPolicyResponse) { return this->GetCertPathValidationPolicy(NULL, NULL, ns1__GetCertPathValidationPolicy, ns1__GetCertPathValidationPolicyResponse); }
        /// Web service synchronous operation 'GetCertPathValidationPolicy' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetCertPathValidationPolicy(const char *soap_endpoint_url, const char *soap_action, _ns1__GetCertPathValidationPolicy *ns1__GetCertPathValidationPolicy, _ns1__GetCertPathValidationPolicyResponse &ns1__GetCertPathValidationPolicyResponse) { return this->send_GetCertPathValidationPolicy(soap_endpoint_url, soap_action, ns1__GetCertPathValidationPolicy) || this->recv_GetCertPathValidationPolicy(ns1__GetCertPathValidationPolicyResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetCertPathValidationPolicy' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetCertPathValidationPolicy(const char *soap_endpoint_url, const char *soap_action, _ns1__GetCertPathValidationPolicy *ns1__GetCertPathValidationPolicy);
        /// Web service asynchronous operation 'recv_GetCertPathValidationPolicy' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetCertPathValidationPolicy(_ns1__GetCertPathValidationPolicyResponse &ns1__GetCertPathValidationPolicyResponse);
        //
        /// Web service synchronous operation 'GetAllCertPathValidationPolicies' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetAllCertPathValidationPolicies(_ns1__GetAllCertPathValidationPolicies *ns1__GetAllCertPathValidationPolicies, _ns1__GetAllCertPathValidationPoliciesResponse &ns1__GetAllCertPathValidationPoliciesResponse) { return this->GetAllCertPathValidationPolicies(NULL, NULL, ns1__GetAllCertPathValidationPolicies, ns1__GetAllCertPathValidationPoliciesResponse); }
        /// Web service synchronous operation 'GetAllCertPathValidationPolicies' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetAllCertPathValidationPolicies(const char *soap_endpoint_url, const char *soap_action, _ns1__GetAllCertPathValidationPolicies *ns1__GetAllCertPathValidationPolicies, _ns1__GetAllCertPathValidationPoliciesResponse &ns1__GetAllCertPathValidationPoliciesResponse) { return this->send_GetAllCertPathValidationPolicies(soap_endpoint_url, soap_action, ns1__GetAllCertPathValidationPolicies) || this->recv_GetAllCertPathValidationPolicies(ns1__GetAllCertPathValidationPoliciesResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetAllCertPathValidationPolicies' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetAllCertPathValidationPolicies(const char *soap_endpoint_url, const char *soap_action, _ns1__GetAllCertPathValidationPolicies *ns1__GetAllCertPathValidationPolicies);
        /// Web service asynchronous operation 'recv_GetAllCertPathValidationPolicies' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetAllCertPathValidationPolicies(_ns1__GetAllCertPathValidationPoliciesResponse &ns1__GetAllCertPathValidationPoliciesResponse);
        //
        /// Web service synchronous operation 'DeleteCertPathValidationPolicy' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int DeleteCertPathValidationPolicy(_ns1__DeleteCertPathValidationPolicy *ns1__DeleteCertPathValidationPolicy, _ns1__DeleteCertPathValidationPolicyResponse &ns1__DeleteCertPathValidationPolicyResponse) { return this->DeleteCertPathValidationPolicy(NULL, NULL, ns1__DeleteCertPathValidationPolicy, ns1__DeleteCertPathValidationPolicyResponse); }
        /// Web service synchronous operation 'DeleteCertPathValidationPolicy' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int DeleteCertPathValidationPolicy(const char *soap_endpoint_url, const char *soap_action, _ns1__DeleteCertPathValidationPolicy *ns1__DeleteCertPathValidationPolicy, _ns1__DeleteCertPathValidationPolicyResponse &ns1__DeleteCertPathValidationPolicyResponse) { return this->send_DeleteCertPathValidationPolicy(soap_endpoint_url, soap_action, ns1__DeleteCertPathValidationPolicy) || this->recv_DeleteCertPathValidationPolicy(ns1__DeleteCertPathValidationPolicyResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_DeleteCertPathValidationPolicy' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_DeleteCertPathValidationPolicy(const char *soap_endpoint_url, const char *soap_action, _ns1__DeleteCertPathValidationPolicy *ns1__DeleteCertPathValidationPolicy);
        /// Web service asynchronous operation 'recv_DeleteCertPathValidationPolicy' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_DeleteCertPathValidationPolicy(_ns1__DeleteCertPathValidationPolicyResponse &ns1__DeleteCertPathValidationPolicyResponse);
        //
        /// Web service synchronous operation 'AddServerCertificateAssignment' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int AddServerCertificateAssignment(_ns1__AddServerCertificateAssignment *ns1__AddServerCertificateAssignment, _ns1__AddServerCertificateAssignmentResponse &ns1__AddServerCertificateAssignmentResponse) { return this->AddServerCertificateAssignment(NULL, NULL, ns1__AddServerCertificateAssignment, ns1__AddServerCertificateAssignmentResponse); }
        /// Web service synchronous operation 'AddServerCertificateAssignment' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int AddServerCertificateAssignment(const char *soap_endpoint_url, const char *soap_action, _ns1__AddServerCertificateAssignment *ns1__AddServerCertificateAssignment, _ns1__AddServerCertificateAssignmentResponse &ns1__AddServerCertificateAssignmentResponse) { return this->send_AddServerCertificateAssignment(soap_endpoint_url, soap_action, ns1__AddServerCertificateAssignment) || this->recv_AddServerCertificateAssignment(ns1__AddServerCertificateAssignmentResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_AddServerCertificateAssignment' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_AddServerCertificateAssignment(const char *soap_endpoint_url, const char *soap_action, _ns1__AddServerCertificateAssignment *ns1__AddServerCertificateAssignment);
        /// Web service asynchronous operation 'recv_AddServerCertificateAssignment' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_AddServerCertificateAssignment(_ns1__AddServerCertificateAssignmentResponse &ns1__AddServerCertificateAssignmentResponse);
        //
        /// Web service synchronous operation 'RemoveServerCertificateAssignment' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int RemoveServerCertificateAssignment(_ns1__RemoveServerCertificateAssignment *ns1__RemoveServerCertificateAssignment, _ns1__RemoveServerCertificateAssignmentResponse &ns1__RemoveServerCertificateAssignmentResponse) { return this->RemoveServerCertificateAssignment(NULL, NULL, ns1__RemoveServerCertificateAssignment, ns1__RemoveServerCertificateAssignmentResponse); }
        /// Web service synchronous operation 'RemoveServerCertificateAssignment' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int RemoveServerCertificateAssignment(const char *soap_endpoint_url, const char *soap_action, _ns1__RemoveServerCertificateAssignment *ns1__RemoveServerCertificateAssignment, _ns1__RemoveServerCertificateAssignmentResponse &ns1__RemoveServerCertificateAssignmentResponse) { return this->send_RemoveServerCertificateAssignment(soap_endpoint_url, soap_action, ns1__RemoveServerCertificateAssignment) || this->recv_RemoveServerCertificateAssignment(ns1__RemoveServerCertificateAssignmentResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_RemoveServerCertificateAssignment' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_RemoveServerCertificateAssignment(const char *soap_endpoint_url, const char *soap_action, _ns1__RemoveServerCertificateAssignment *ns1__RemoveServerCertificateAssignment);
        /// Web service asynchronous operation 'recv_RemoveServerCertificateAssignment' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_RemoveServerCertificateAssignment(_ns1__RemoveServerCertificateAssignmentResponse &ns1__RemoveServerCertificateAssignmentResponse);
        //
        /// Web service synchronous operation 'ReplaceServerCertificateAssignment' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int ReplaceServerCertificateAssignment(_ns1__ReplaceServerCertificateAssignment *ns1__ReplaceServerCertificateAssignment, _ns1__ReplaceServerCertificateAssignmentResponse &ns1__ReplaceServerCertificateAssignmentResponse) { return this->ReplaceServerCertificateAssignment(NULL, NULL, ns1__ReplaceServerCertificateAssignment, ns1__ReplaceServerCertificateAssignmentResponse); }
        /// Web service synchronous operation 'ReplaceServerCertificateAssignment' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int ReplaceServerCertificateAssignment(const char *soap_endpoint_url, const char *soap_action, _ns1__ReplaceServerCertificateAssignment *ns1__ReplaceServerCertificateAssignment, _ns1__ReplaceServerCertificateAssignmentResponse &ns1__ReplaceServerCertificateAssignmentResponse) { return this->send_ReplaceServerCertificateAssignment(soap_endpoint_url, soap_action, ns1__ReplaceServerCertificateAssignment) || this->recv_ReplaceServerCertificateAssignment(ns1__ReplaceServerCertificateAssignmentResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_ReplaceServerCertificateAssignment' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_ReplaceServerCertificateAssignment(const char *soap_endpoint_url, const char *soap_action, _ns1__ReplaceServerCertificateAssignment *ns1__ReplaceServerCertificateAssignment);
        /// Web service asynchronous operation 'recv_ReplaceServerCertificateAssignment' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_ReplaceServerCertificateAssignment(_ns1__ReplaceServerCertificateAssignmentResponse &ns1__ReplaceServerCertificateAssignmentResponse);
        //
        /// Web service synchronous operation 'GetAssignedServerCertificates' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetAssignedServerCertificates(_ns1__GetAssignedServerCertificates *ns1__GetAssignedServerCertificates, _ns1__GetAssignedServerCertificatesResponse &ns1__GetAssignedServerCertificatesResponse) { return this->GetAssignedServerCertificates(NULL, NULL, ns1__GetAssignedServerCertificates, ns1__GetAssignedServerCertificatesResponse); }
        /// Web service synchronous operation 'GetAssignedServerCertificates' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetAssignedServerCertificates(const char *soap_endpoint_url, const char *soap_action, _ns1__GetAssignedServerCertificates *ns1__GetAssignedServerCertificates, _ns1__GetAssignedServerCertificatesResponse &ns1__GetAssignedServerCertificatesResponse) { return this->send_GetAssignedServerCertificates(soap_endpoint_url, soap_action, ns1__GetAssignedServerCertificates) || this->recv_GetAssignedServerCertificates(ns1__GetAssignedServerCertificatesResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetAssignedServerCertificates' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetAssignedServerCertificates(const char *soap_endpoint_url, const char *soap_action, _ns1__GetAssignedServerCertificates *ns1__GetAssignedServerCertificates);
        /// Web service asynchronous operation 'recv_GetAssignedServerCertificates' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetAssignedServerCertificates(_ns1__GetAssignedServerCertificatesResponse &ns1__GetAssignedServerCertificatesResponse);
        //
        /// Web service synchronous operation 'SetEnabledTLSVersions' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int SetEnabledTLSVersions(_ns1__SetEnabledTLSVersions *ns1__SetEnabledTLSVersions, _ns1__SetEnabledTLSVersionsResponse &ns1__SetEnabledTLSVersionsResponse) { return this->SetEnabledTLSVersions(NULL, NULL, ns1__SetEnabledTLSVersions, ns1__SetEnabledTLSVersionsResponse); }
        /// Web service synchronous operation 'SetEnabledTLSVersions' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int SetEnabledTLSVersions(const char *soap_endpoint_url, const char *soap_action, _ns1__SetEnabledTLSVersions *ns1__SetEnabledTLSVersions, _ns1__SetEnabledTLSVersionsResponse &ns1__SetEnabledTLSVersionsResponse) { return this->send_SetEnabledTLSVersions(soap_endpoint_url, soap_action, ns1__SetEnabledTLSVersions) || this->recv_SetEnabledTLSVersions(ns1__SetEnabledTLSVersionsResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_SetEnabledTLSVersions' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_SetEnabledTLSVersions(const char *soap_endpoint_url, const char *soap_action, _ns1__SetEnabledTLSVersions *ns1__SetEnabledTLSVersions);
        /// Web service asynchronous operation 'recv_SetEnabledTLSVersions' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_SetEnabledTLSVersions(_ns1__SetEnabledTLSVersionsResponse &ns1__SetEnabledTLSVersionsResponse);
        //
        /// Web service synchronous operation 'GetEnabledTLSVersions' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetEnabledTLSVersions(_ns1__GetEnabledTLSVersions *ns1__GetEnabledTLSVersions, _ns1__GetEnabledTLSVersionsResponse &ns1__GetEnabledTLSVersionsResponse) { return this->GetEnabledTLSVersions(NULL, NULL, ns1__GetEnabledTLSVersions, ns1__GetEnabledTLSVersionsResponse); }
        /// Web service synchronous operation 'GetEnabledTLSVersions' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetEnabledTLSVersions(const char *soap_endpoint_url, const char *soap_action, _ns1__GetEnabledTLSVersions *ns1__GetEnabledTLSVersions, _ns1__GetEnabledTLSVersionsResponse &ns1__GetEnabledTLSVersionsResponse) { return this->send_GetEnabledTLSVersions(soap_endpoint_url, soap_action, ns1__GetEnabledTLSVersions) || this->recv_GetEnabledTLSVersions(ns1__GetEnabledTLSVersionsResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetEnabledTLSVersions' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetEnabledTLSVersions(const char *soap_endpoint_url, const char *soap_action, _ns1__GetEnabledTLSVersions *ns1__GetEnabledTLSVersions);
        /// Web service asynchronous operation 'recv_GetEnabledTLSVersions' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetEnabledTLSVersions(_ns1__GetEnabledTLSVersionsResponse &ns1__GetEnabledTLSVersionsResponse);
        //
        /// Web service synchronous operation 'SetClientAuthenticationRequired' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int SetClientAuthenticationRequired(_ns1__SetClientAuthenticationRequired *ns1__SetClientAuthenticationRequired, _ns1__SetClientAuthenticationRequiredResponse &ns1__SetClientAuthenticationRequiredResponse) { return this->SetClientAuthenticationRequired(NULL, NULL, ns1__SetClientAuthenticationRequired, ns1__SetClientAuthenticationRequiredResponse); }
        /// Web service synchronous operation 'SetClientAuthenticationRequired' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int SetClientAuthenticationRequired(const char *soap_endpoint_url, const char *soap_action, _ns1__SetClientAuthenticationRequired *ns1__SetClientAuthenticationRequired, _ns1__SetClientAuthenticationRequiredResponse &ns1__SetClientAuthenticationRequiredResponse) { return this->send_SetClientAuthenticationRequired(soap_endpoint_url, soap_action, ns1__SetClientAuthenticationRequired) || this->recv_SetClientAuthenticationRequired(ns1__SetClientAuthenticationRequiredResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_SetClientAuthenticationRequired' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_SetClientAuthenticationRequired(const char *soap_endpoint_url, const char *soap_action, _ns1__SetClientAuthenticationRequired *ns1__SetClientAuthenticationRequired);
        /// Web service asynchronous operation 'recv_SetClientAuthenticationRequired' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_SetClientAuthenticationRequired(_ns1__SetClientAuthenticationRequiredResponse &ns1__SetClientAuthenticationRequiredResponse);
        //
        /// Web service synchronous operation 'GetClientAuthenticationRequired' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetClientAuthenticationRequired(_ns1__GetClientAuthenticationRequired *ns1__GetClientAuthenticationRequired, _ns1__GetClientAuthenticationRequiredResponse &ns1__GetClientAuthenticationRequiredResponse) { return this->GetClientAuthenticationRequired(NULL, NULL, ns1__GetClientAuthenticationRequired, ns1__GetClientAuthenticationRequiredResponse); }
        /// Web service synchronous operation 'GetClientAuthenticationRequired' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetClientAuthenticationRequired(const char *soap_endpoint_url, const char *soap_action, _ns1__GetClientAuthenticationRequired *ns1__GetClientAuthenticationRequired, _ns1__GetClientAuthenticationRequiredResponse &ns1__GetClientAuthenticationRequiredResponse) { return this->send_GetClientAuthenticationRequired(soap_endpoint_url, soap_action, ns1__GetClientAuthenticationRequired) || this->recv_GetClientAuthenticationRequired(ns1__GetClientAuthenticationRequiredResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetClientAuthenticationRequired' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetClientAuthenticationRequired(const char *soap_endpoint_url, const char *soap_action, _ns1__GetClientAuthenticationRequired *ns1__GetClientAuthenticationRequired);
        /// Web service asynchronous operation 'recv_GetClientAuthenticationRequired' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetClientAuthenticationRequired(_ns1__GetClientAuthenticationRequiredResponse &ns1__GetClientAuthenticationRequiredResponse);
        //
        /// Web service synchronous operation 'AddCertPathValidationPolicyAssignment' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int AddCertPathValidationPolicyAssignment(_ns1__AddCertPathValidationPolicyAssignment *ns1__AddCertPathValidationPolicyAssignment, _ns1__AddCertPathValidationPolicyAssignmentResponse &ns1__AddCertPathValidationPolicyAssignmentResponse) { return this->AddCertPathValidationPolicyAssignment(NULL, NULL, ns1__AddCertPathValidationPolicyAssignment, ns1__AddCertPathValidationPolicyAssignmentResponse); }
        /// Web service synchronous operation 'AddCertPathValidationPolicyAssignment' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int AddCertPathValidationPolicyAssignment(const char *soap_endpoint_url, const char *soap_action, _ns1__AddCertPathValidationPolicyAssignment *ns1__AddCertPathValidationPolicyAssignment, _ns1__AddCertPathValidationPolicyAssignmentResponse &ns1__AddCertPathValidationPolicyAssignmentResponse) { return this->send_AddCertPathValidationPolicyAssignment(soap_endpoint_url, soap_action, ns1__AddCertPathValidationPolicyAssignment) || this->recv_AddCertPathValidationPolicyAssignment(ns1__AddCertPathValidationPolicyAssignmentResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_AddCertPathValidationPolicyAssignment' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_AddCertPathValidationPolicyAssignment(const char *soap_endpoint_url, const char *soap_action, _ns1__AddCertPathValidationPolicyAssignment *ns1__AddCertPathValidationPolicyAssignment);
        /// Web service asynchronous operation 'recv_AddCertPathValidationPolicyAssignment' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_AddCertPathValidationPolicyAssignment(_ns1__AddCertPathValidationPolicyAssignmentResponse &ns1__AddCertPathValidationPolicyAssignmentResponse);
        //
        /// Web service synchronous operation 'RemoveCertPathValidationPolicyAssignment' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int RemoveCertPathValidationPolicyAssignment(_ns1__RemoveCertPathValidationPolicyAssignment *ns1__RemoveCertPathValidationPolicyAssignment, _ns1__RemoveCertPathValidationPolicyAssignmentResponse &ns1__RemoveCertPathValidationPolicyAssignmentResponse) { return this->RemoveCertPathValidationPolicyAssignment(NULL, NULL, ns1__RemoveCertPathValidationPolicyAssignment, ns1__RemoveCertPathValidationPolicyAssignmentResponse); }
        /// Web service synchronous operation 'RemoveCertPathValidationPolicyAssignment' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int RemoveCertPathValidationPolicyAssignment(const char *soap_endpoint_url, const char *soap_action, _ns1__RemoveCertPathValidationPolicyAssignment *ns1__RemoveCertPathValidationPolicyAssignment, _ns1__RemoveCertPathValidationPolicyAssignmentResponse &ns1__RemoveCertPathValidationPolicyAssignmentResponse) { return this->send_RemoveCertPathValidationPolicyAssignment(soap_endpoint_url, soap_action, ns1__RemoveCertPathValidationPolicyAssignment) || this->recv_RemoveCertPathValidationPolicyAssignment(ns1__RemoveCertPathValidationPolicyAssignmentResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_RemoveCertPathValidationPolicyAssignment' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_RemoveCertPathValidationPolicyAssignment(const char *soap_endpoint_url, const char *soap_action, _ns1__RemoveCertPathValidationPolicyAssignment *ns1__RemoveCertPathValidationPolicyAssignment);
        /// Web service asynchronous operation 'recv_RemoveCertPathValidationPolicyAssignment' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_RemoveCertPathValidationPolicyAssignment(_ns1__RemoveCertPathValidationPolicyAssignmentResponse &ns1__RemoveCertPathValidationPolicyAssignmentResponse);
        //
        /// Web service synchronous operation 'ReplaceCertPathValidationPolicyAssignment' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int ReplaceCertPathValidationPolicyAssignment(_ns1__ReplaceCertPathValidationPolicyAssignment *ns1__ReplaceCertPathValidationPolicyAssignment, _ns1__ReplaceCertPathValidationPolicyAssignmentResponse &ns1__ReplaceCertPathValidationPolicyAssignmentResponse) { return this->ReplaceCertPathValidationPolicyAssignment(NULL, NULL, ns1__ReplaceCertPathValidationPolicyAssignment, ns1__ReplaceCertPathValidationPolicyAssignmentResponse); }
        /// Web service synchronous operation 'ReplaceCertPathValidationPolicyAssignment' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int ReplaceCertPathValidationPolicyAssignment(const char *soap_endpoint_url, const char *soap_action, _ns1__ReplaceCertPathValidationPolicyAssignment *ns1__ReplaceCertPathValidationPolicyAssignment, _ns1__ReplaceCertPathValidationPolicyAssignmentResponse &ns1__ReplaceCertPathValidationPolicyAssignmentResponse) { return this->send_ReplaceCertPathValidationPolicyAssignment(soap_endpoint_url, soap_action, ns1__ReplaceCertPathValidationPolicyAssignment) || this->recv_ReplaceCertPathValidationPolicyAssignment(ns1__ReplaceCertPathValidationPolicyAssignmentResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_ReplaceCertPathValidationPolicyAssignment' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_ReplaceCertPathValidationPolicyAssignment(const char *soap_endpoint_url, const char *soap_action, _ns1__ReplaceCertPathValidationPolicyAssignment *ns1__ReplaceCertPathValidationPolicyAssignment);
        /// Web service asynchronous operation 'recv_ReplaceCertPathValidationPolicyAssignment' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_ReplaceCertPathValidationPolicyAssignment(_ns1__ReplaceCertPathValidationPolicyAssignmentResponse &ns1__ReplaceCertPathValidationPolicyAssignmentResponse);
        //
        /// Web service synchronous operation 'GetAssignedCertPathValidationPolicies' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetAssignedCertPathValidationPolicies(_ns1__GetAssignedCertPathValidationPolicies *ns1__GetAssignedCertPathValidationPolicies, _ns1__GetAssignedCertPathValidationPoliciesResponse &ns1__GetAssignedCertPathValidationPoliciesResponse) { return this->GetAssignedCertPathValidationPolicies(NULL, NULL, ns1__GetAssignedCertPathValidationPolicies, ns1__GetAssignedCertPathValidationPoliciesResponse); }
        /// Web service synchronous operation 'GetAssignedCertPathValidationPolicies' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetAssignedCertPathValidationPolicies(const char *soap_endpoint_url, const char *soap_action, _ns1__GetAssignedCertPathValidationPolicies *ns1__GetAssignedCertPathValidationPolicies, _ns1__GetAssignedCertPathValidationPoliciesResponse &ns1__GetAssignedCertPathValidationPoliciesResponse) { return this->send_GetAssignedCertPathValidationPolicies(soap_endpoint_url, soap_action, ns1__GetAssignedCertPathValidationPolicies) || this->recv_GetAssignedCertPathValidationPolicies(ns1__GetAssignedCertPathValidationPoliciesResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetAssignedCertPathValidationPolicies' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetAssignedCertPathValidationPolicies(const char *soap_endpoint_url, const char *soap_action, _ns1__GetAssignedCertPathValidationPolicies *ns1__GetAssignedCertPathValidationPolicies);
        /// Web service asynchronous operation 'recv_GetAssignedCertPathValidationPolicies' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetAssignedCertPathValidationPolicies(_ns1__GetAssignedCertPathValidationPoliciesResponse &ns1__GetAssignedCertPathValidationPoliciesResponse);
        //
        /// Web service synchronous operation 'AddDot1XConfiguration' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int AddDot1XConfiguration(_ns1__AddDot1XConfiguration *ns1__AddDot1XConfiguration, _ns1__AddDot1XConfigurationResponse &ns1__AddDot1XConfigurationResponse) { return this->AddDot1XConfiguration(NULL, NULL, ns1__AddDot1XConfiguration, ns1__AddDot1XConfigurationResponse); }
        /// Web service synchronous operation 'AddDot1XConfiguration' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int AddDot1XConfiguration(const char *soap_endpoint_url, const char *soap_action, _ns1__AddDot1XConfiguration *ns1__AddDot1XConfiguration, _ns1__AddDot1XConfigurationResponse &ns1__AddDot1XConfigurationResponse) { return this->send_AddDot1XConfiguration(soap_endpoint_url, soap_action, ns1__AddDot1XConfiguration) || this->recv_AddDot1XConfiguration(ns1__AddDot1XConfigurationResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_AddDot1XConfiguration' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_AddDot1XConfiguration(const char *soap_endpoint_url, const char *soap_action, _ns1__AddDot1XConfiguration *ns1__AddDot1XConfiguration);
        /// Web service asynchronous operation 'recv_AddDot1XConfiguration' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_AddDot1XConfiguration(_ns1__AddDot1XConfigurationResponse &ns1__AddDot1XConfigurationResponse);
        //
        /// Web service synchronous operation 'GetAllDot1XConfigurations' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetAllDot1XConfigurations(_ns1__GetAllDot1XConfigurations *ns1__GetAllDot1XConfigurations, _ns1__GetAllDot1XConfigurationsResponse &ns1__GetAllDot1XConfigurationsResponse) { return this->GetAllDot1XConfigurations(NULL, NULL, ns1__GetAllDot1XConfigurations, ns1__GetAllDot1XConfigurationsResponse); }
        /// Web service synchronous operation 'GetAllDot1XConfigurations' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetAllDot1XConfigurations(const char *soap_endpoint_url, const char *soap_action, _ns1__GetAllDot1XConfigurations *ns1__GetAllDot1XConfigurations, _ns1__GetAllDot1XConfigurationsResponse &ns1__GetAllDot1XConfigurationsResponse) { return this->send_GetAllDot1XConfigurations(soap_endpoint_url, soap_action, ns1__GetAllDot1XConfigurations) || this->recv_GetAllDot1XConfigurations(ns1__GetAllDot1XConfigurationsResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetAllDot1XConfigurations' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetAllDot1XConfigurations(const char *soap_endpoint_url, const char *soap_action, _ns1__GetAllDot1XConfigurations *ns1__GetAllDot1XConfigurations);
        /// Web service asynchronous operation 'recv_GetAllDot1XConfigurations' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetAllDot1XConfigurations(_ns1__GetAllDot1XConfigurationsResponse &ns1__GetAllDot1XConfigurationsResponse);
        //
        /// Web service synchronous operation 'GetDot1XConfiguration' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetDot1XConfiguration(_ns1__GetDot1XConfiguration *ns1__GetDot1XConfiguration, _ns1__GetDot1XConfigurationResponse &ns1__GetDot1XConfigurationResponse) { return this->GetDot1XConfiguration(NULL, NULL, ns1__GetDot1XConfiguration, ns1__GetDot1XConfigurationResponse); }
        /// Web service synchronous operation 'GetDot1XConfiguration' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetDot1XConfiguration(const char *soap_endpoint_url, const char *soap_action, _ns1__GetDot1XConfiguration *ns1__GetDot1XConfiguration, _ns1__GetDot1XConfigurationResponse &ns1__GetDot1XConfigurationResponse) { return this->send_GetDot1XConfiguration(soap_endpoint_url, soap_action, ns1__GetDot1XConfiguration) || this->recv_GetDot1XConfiguration(ns1__GetDot1XConfigurationResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetDot1XConfiguration' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetDot1XConfiguration(const char *soap_endpoint_url, const char *soap_action, _ns1__GetDot1XConfiguration *ns1__GetDot1XConfiguration);
        /// Web service asynchronous operation 'recv_GetDot1XConfiguration' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetDot1XConfiguration(_ns1__GetDot1XConfigurationResponse &ns1__GetDot1XConfigurationResponse);
        //
        /// Web service synchronous operation 'DeleteDot1XConfiguration' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int DeleteDot1XConfiguration(_ns1__DeleteDot1XConfiguration *ns1__DeleteDot1XConfiguration, _ns1__DeleteDot1XConfigurationResponse &ns1__DeleteDot1XConfigurationResponse) { return this->DeleteDot1XConfiguration(NULL, NULL, ns1__DeleteDot1XConfiguration, ns1__DeleteDot1XConfigurationResponse); }
        /// Web service synchronous operation 'DeleteDot1XConfiguration' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int DeleteDot1XConfiguration(const char *soap_endpoint_url, const char *soap_action, _ns1__DeleteDot1XConfiguration *ns1__DeleteDot1XConfiguration, _ns1__DeleteDot1XConfigurationResponse &ns1__DeleteDot1XConfigurationResponse) { return this->send_DeleteDot1XConfiguration(soap_endpoint_url, soap_action, ns1__DeleteDot1XConfiguration) || this->recv_DeleteDot1XConfiguration(ns1__DeleteDot1XConfigurationResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_DeleteDot1XConfiguration' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_DeleteDot1XConfiguration(const char *soap_endpoint_url, const char *soap_action, _ns1__DeleteDot1XConfiguration *ns1__DeleteDot1XConfiguration);
        /// Web service asynchronous operation 'recv_DeleteDot1XConfiguration' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_DeleteDot1XConfiguration(_ns1__DeleteDot1XConfigurationResponse &ns1__DeleteDot1XConfigurationResponse);
        //
        /// Web service synchronous operation 'SetNetworkInterfaceDot1XConfiguration' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int SetNetworkInterfaceDot1XConfiguration(_ns1__SetNetworkInterfaceDot1XConfiguration *ns1__SetNetworkInterfaceDot1XConfiguration, _ns1__SetNetworkInterfaceDot1XConfigurationResponse &ns1__SetNetworkInterfaceDot1XConfigurationResponse) { return this->SetNetworkInterfaceDot1XConfiguration(NULL, NULL, ns1__SetNetworkInterfaceDot1XConfiguration, ns1__SetNetworkInterfaceDot1XConfigurationResponse); }
        /// Web service synchronous operation 'SetNetworkInterfaceDot1XConfiguration' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int SetNetworkInterfaceDot1XConfiguration(const char *soap_endpoint_url, const char *soap_action, _ns1__SetNetworkInterfaceDot1XConfiguration *ns1__SetNetworkInterfaceDot1XConfiguration, _ns1__SetNetworkInterfaceDot1XConfigurationResponse &ns1__SetNetworkInterfaceDot1XConfigurationResponse) { return this->send_SetNetworkInterfaceDot1XConfiguration(soap_endpoint_url, soap_action, ns1__SetNetworkInterfaceDot1XConfiguration) || this->recv_SetNetworkInterfaceDot1XConfiguration(ns1__SetNetworkInterfaceDot1XConfigurationResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_SetNetworkInterfaceDot1XConfiguration' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_SetNetworkInterfaceDot1XConfiguration(const char *soap_endpoint_url, const char *soap_action, _ns1__SetNetworkInterfaceDot1XConfiguration *ns1__SetNetworkInterfaceDot1XConfiguration);
        /// Web service asynchronous operation 'recv_SetNetworkInterfaceDot1XConfiguration' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_SetNetworkInterfaceDot1XConfiguration(_ns1__SetNetworkInterfaceDot1XConfigurationResponse &ns1__SetNetworkInterfaceDot1XConfigurationResponse);
        //
        /// Web service synchronous operation 'GetNetworkInterfaceDot1XConfiguration' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetNetworkInterfaceDot1XConfiguration(_ns1__GetNetworkInterfaceDot1XConfiguration *ns1__GetNetworkInterfaceDot1XConfiguration, _ns1__GetNetworkInterfaceDot1XConfigurationResponse &ns1__GetNetworkInterfaceDot1XConfigurationResponse) { return this->GetNetworkInterfaceDot1XConfiguration(NULL, NULL, ns1__GetNetworkInterfaceDot1XConfiguration, ns1__GetNetworkInterfaceDot1XConfigurationResponse); }
        /// Web service synchronous operation 'GetNetworkInterfaceDot1XConfiguration' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetNetworkInterfaceDot1XConfiguration(const char *soap_endpoint_url, const char *soap_action, _ns1__GetNetworkInterfaceDot1XConfiguration *ns1__GetNetworkInterfaceDot1XConfiguration, _ns1__GetNetworkInterfaceDot1XConfigurationResponse &ns1__GetNetworkInterfaceDot1XConfigurationResponse) { return this->send_GetNetworkInterfaceDot1XConfiguration(soap_endpoint_url, soap_action, ns1__GetNetworkInterfaceDot1XConfiguration) || this->recv_GetNetworkInterfaceDot1XConfiguration(ns1__GetNetworkInterfaceDot1XConfigurationResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetNetworkInterfaceDot1XConfiguration' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetNetworkInterfaceDot1XConfiguration(const char *soap_endpoint_url, const char *soap_action, _ns1__GetNetworkInterfaceDot1XConfiguration *ns1__GetNetworkInterfaceDot1XConfiguration);
        /// Web service asynchronous operation 'recv_GetNetworkInterfaceDot1XConfiguration' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetNetworkInterfaceDot1XConfiguration(_ns1__GetNetworkInterfaceDot1XConfigurationResponse &ns1__GetNetworkInterfaceDot1XConfigurationResponse);
        //
        /// Web service synchronous operation 'DeleteNetworkInterfaceDot1XConfiguration' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int DeleteNetworkInterfaceDot1XConfiguration(_ns1__DeleteNetworkInterfaceDot1XConfiguration *ns1__DeleteNetworkInterfaceDot1XConfiguration, _ns1__DeleteNetworkInterfaceDot1XConfigurationResponse &ns1__DeleteNetworkInterfaceDot1XConfigurationResponse) { return this->DeleteNetworkInterfaceDot1XConfiguration(NULL, NULL, ns1__DeleteNetworkInterfaceDot1XConfiguration, ns1__DeleteNetworkInterfaceDot1XConfigurationResponse); }
        /// Web service synchronous operation 'DeleteNetworkInterfaceDot1XConfiguration' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int DeleteNetworkInterfaceDot1XConfiguration(const char *soap_endpoint_url, const char *soap_action, _ns1__DeleteNetworkInterfaceDot1XConfiguration *ns1__DeleteNetworkInterfaceDot1XConfiguration, _ns1__DeleteNetworkInterfaceDot1XConfigurationResponse &ns1__DeleteNetworkInterfaceDot1XConfigurationResponse) { return this->send_DeleteNetworkInterfaceDot1XConfiguration(soap_endpoint_url, soap_action, ns1__DeleteNetworkInterfaceDot1XConfiguration) || this->recv_DeleteNetworkInterfaceDot1XConfiguration(ns1__DeleteNetworkInterfaceDot1XConfigurationResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_DeleteNetworkInterfaceDot1XConfiguration' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_DeleteNetworkInterfaceDot1XConfiguration(const char *soap_endpoint_url, const char *soap_action, _ns1__DeleteNetworkInterfaceDot1XConfiguration *ns1__DeleteNetworkInterfaceDot1XConfiguration);
        /// Web service asynchronous operation 'recv_DeleteNetworkInterfaceDot1XConfiguration' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_DeleteNetworkInterfaceDot1XConfiguration(_ns1__DeleteNetworkInterfaceDot1XConfigurationResponse &ns1__DeleteNetworkInterfaceDot1XConfigurationResponse);
    };
#endif
